name: Terraform Init & Plan

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ./module  # Adjust if your Terraform root is elsewhere

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      #- name: Terraform Format Check
      #  run: terraform -chdir=${{ env.TF_WORKING_DIR }} fmt -check

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan
